version: '3'

services:
  frontend:
    container_name: "codebase-react-18-cra"
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    ports:
      - "4002:4002"
    stdin_open: true
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
